### ISSUE TITLE
bkcrack -L gives encryption method "Other" despite it being ZipCrypto

### ISSUE THREAD

**Issue by LiEnby** [kimci86/bkcrack#104]
according to 7-zip the first_pss.arc file is encrypted using the standard ZipCrypto
![image](https://github.com/kimci86/bkcrack/assets/39113159/45b5942a-bbf7-4f75-ac43-7dc3bcf816f4)
but when i run the command to list the entries in bkcrack it says its an "Other" format
![image](https://github.com/kimci86/bkcrack/assets/39113159/727e8042-03ea-4583-b1f2-ff95c8a9d415)

you can find the zip file here:
http://zeus.dl.playstation.net/pss/cGxheXN0YXRpb25z/content/JP9000/NPMK00001_00/NPMK00001_00_1.zpak

**Comment by kimci86** [comment]
This file is a ZIP file with some non-standard extension to the format. It might be a Sony specific extension. 7-zip gets confused parsing it.
I am not sure what encryption is used exactly. However, looking at packed file sizes, I can tell there is probably no compression and a block-cipher was used because all the packed sizes are the first multiple or 16 greater or equal to uncompressed size. It might be some AES encryption. Anyways I can assure you it is not ZipCrypto.

So it looks to me that `bkcrack -L` output looks correct.
You will not be able to crack this file using bkcrack.
