### ISSUE TITLE
Accelerated by GPU

### ISSUE THREAD

**Issue by cnbac** [kimci86/bkcrack#110]
Greetings!

I thought of a way
Create a 12-byte file with all zeros
Then pass the offset parameter from 0 to 1000
Used to process exe files in ZipCrypto store
i pass
bkcrack.exe -C 1.zip -c 1.exe -p 12zeros -o (32-64)
Test, very slow
Is it possible to accelerate this method with GPU

Sorry, I don't know English, from translator

Thank you.

**Comment by kimci86** [comment]
Hi,
Maybe GPU could speed up this approach, but in the case of an .exe file, this approach is a waste of time anyways. It will be much faster to give more known plaintext. As far as I know, all .exe files start with the same 60 bytes (part of the DOS header). So a single run is needed because the offset is known (it is 0) and with that much information, bkcrack will run in a couple of minutes at most.

Try this:

    bkcrack.exe -C 1.zip -c 1.exe -p bkcrack.exe -t 60

**Comment by kimci86** [comment]
I'm closing the discussion in the absence of feedback.
