### ISSUE TITLE
Chinese encoding error - 中文编码错误

### ISSUE THREAD

**Issue by xmexg** [kimci86/bkcrack#115]
Can not use `-c` to find files when there are Chinese characters in the zip

like: GBK in .zip -- UTF-8 in Computer(linux and windows)  
![IMG_20240318_080744](https://github.com/kimci86/bkcrack/assets/42137636/bea12d4a-32df-41a1-a65a-da4868c16db7)

How to reproduce:  
mkdir 这是中文路径   
cp one_file 这是中文路径  
zip -r archive.zip 这是中文路径  -Ppassword
Better switch to a different encoded operating system  
bkcrack -L archive.zip  
let's try `-c 这是中文路径/one_file`

**Comment by Aloxaf** [comment]
This is a ZIP issue, it encodes the filename with system locale encoding instead of UTF-8.

There are two solutions: allowing users to manually specify the encoding (unzip-iconv) or automatically guessing the encoding (unarchiver).
But I'm not sure if this is necessary for a zip cracking tool.

**Comment by xmexg** [comment]
[ebsite-update-2.29-simple.zip](https://github.com/kimci86/bkcrack/files/14645214/ebsite-update-2.29-simple.zip)  
password is `MirlKoi`  

`--cipher-index` is useful.

I deleted some files in zip, and now `-L` is garbled.
![image](https://github.com/kimci86/bkcrack/assets/42137636/b21109bc-75e7-4965-8c0b-6c75a2aae1ba)

**Comment by xmexg** [comment]
I am uploading files to Google Cloud Drive, I will share the link tonight.  
![image](https://github.com/kimci86/bkcrack/assets/42137636/d0b9cbf0-c981-4810-a553-9e70186a1d50)  
![image](https://github.com/kimci86/bkcrack/assets/42137636/c2fd27f4-cdeb-417a-9c73-f11687dcc21c)

**Comment by kimci86** [comment]
Thank you @xmexg for providing the file. I can confirm the ZIP file contains names in GBK encoding or similar. Unfortunately there is no additional metadata in this ZIP archive that could help decode the name right automatically.

Thank you @Aloxaf for your enlightening explanation. You are right, handling encoding correctly in this case would require user input or guessing.

Adding a solution into bkcrack to deal with such a case would be nice, but as there is a workaround with `--cipher-index`, I don't think I'll attempt to implement it any time soon. Probably this deserve more documentation though.

Thank you for reporting the issue and for the feedback.
Do you have more comments about this issue? I will close it otherwise.

**Comment by xmexg** [comment]
thank you

**Comment by xmexg** [comment]
Why can't I get the password?  
![Screenshot_2024-03-20-23-05-01-21_84d3000e3f4017145260f7618db1d683](https://github.com/kimci86/bkcrack/assets/42137636/05ce1b8c-62f4-454c-940c-47a6163ad46f)
![Screenshot_2024-03-20-23-11-12-19_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/kimci86/bkcrack/assets/42137636/45948ec3-b47c-4d8c-80a1-5c9a48c481ed)

**Comment by xmexg** [comment]
Ok, thank you.
