### ISSUE TITLE
Problem with recovered files

### ISSUE THREAD

**Issue by BTCBOY** [kimci86/bkcrack#13]
Sorry to bother you. Following the example I have recovered the keys, extracting the file is not returning what I expect.

Looking at my zipfile, the encrypted file within:
```

Path = Wallets/wallet.dat
Folder = -
Size = 106496
Packed Size = 61288
Modified = 2013-10-01 22:06:50
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = AC7A0D2F
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0
```
When I extract:

`./bkcrack -C Backups.zip -c 'Wallets/wallet.dat' -k KEY  GOES HERE -d wallet.dat.deflate`

I get a file of  61276, not 61288 as in the zip info above.
When I try to deflate I get 

```
Traceback (most recent call last):
  File "tools/inflate.py", line 15, in <module>
    main()
  File "tools/inflate.py", line 12, in main
    sys.stdout.buffer.write(inflate(sys.stdin.buffer.read()))
  File "tools/inflate.py", line 8, in inflate
    return zlib.decompress(data, -zlib.MAX_WBITS)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
```

Any help would be amazing.

**Comment by kimci86** [comment]
Hello,
Regarding the size, packed size includes the 12-byte encryption header which is prepended to compressed data. So the size is good.
Regarding the decompression error, I don't know.
Maybe you can try to use [infgen](https://github.com/madler/infgen/) to examine the deflated data and understand what is wrong.

**Comment by BTCBOY** [comment]
@kimci86 Thanks, I'll give this a try. Does it matter if the 12 byte string I had in `plain.txt` was not from the beginning of the file?

**Comment by kimci86** [comment]
Yes the offset of the known plaintext is an important parameter for an attack to be successful. You should pass it with the `-o` command line parameter.

However, from your last message, I understand you know only a small part of the plaintext. In addition, the encrypted file is also compressed. I am afraid you will not be able to carry out a successful attack in this case because the attack needs known plaintext before encryption, i.e. after compression, so you would need to guess how the file is compressed which is nearly impossible without knowing a substantial part of the input file.

**Comment by BTCBOY** [comment]
@kimci86 thank you for your time and input. For context, I recreated a walled using an old version of the bitcoin software, from that wallet.dat I ran `strings` found 13 contiguous characters which I used as the contents for `plain/txt`, I did not provide the offset for the location of this within the file. Should this approach work?

**Comment by kimci86** [comment]
You are welcome.
The approach described in your last message cannot work with bkcrack. You have to provide a sequence of contiguous bytes (at least 12) at a given offset just before encryption. It means bytes of compressed data in your case.
With only a small part of a wallet.dat file before compression, it is extremely hard to guess a part of the compressed file because deflated data usually starts with a representation of a Huffman tree which depends on an entire block of data.
That being said, I do not know the format used for wallet.dat files. From the compression ratio, it seems to have some regularities.
As a side note, known plaintext does not have to be printable text, it is just a sequence of known bytes.

If by chance there are other files in the encrypted archive, I suggest you try to find plaintext for one of them.
Otherwise, I suggest to try a brute force attack on the archive password with hashcat or john the ripper.
Hope it helps.

**Comment by kimci86** [comment]
I close this as the problem here is to find correct plaintext rather than an issue in bkcrack.
Feel free to reopen it if you need further help.
