### ISSUE TITLE
Data Error When Using bkcrack with Subfolders in ZIP File

### ISSUE THREAD

**Issue by infinity1234** [kimci86/bkcrack#131]
Hello :)

I'm encountering an issue when using `bkcrack` to break the encryption of a ZIP file that contains subfolders. The process works correctly when dealing with a simple file in the root of the ZIP archive, but it fails with an error when the file is within a subfolder.

**Steps to Reproduce:**

1. **This Works:**

   - I created a test file and successfully used `bkcrack` to find the keys:
   
     ```bash
     echo "This is a test file for bkcrack." > testfile.txt
     zip -e testfile.zip testfile.txt
     ./bkcrack/bkcrack -C testfile.zip -c testfile.txt -p testfile.txt
     ```
     - Output:
       ```
       bkcrack 1.7.0 - 2024-05-26
       [03:16:51] Z reduction using 26 bytes of known plaintext
       100.0 % (26 / 26)
       [03:16:52] Attack on 303556 Z values at index 6
       Keys: e0be8d5d 70bb3140 7e983fff
       34.9 % (105873 / 303556)
       Found a solution. Stopping.
       You may resume the attack with the option: --continue-attack 105873
       [03:18:15] Keys
       e0be8d5d 70bb3140 7e983fff
       ```

2. **This Fails:**

   - I created a directory structure with a file inside a subfolder and tried to use `bkcrack`:
   
     ```bash
     mkdir -p testdir/subdir
     echo "This is a test file in the root directory." > testdir/rootfile.txt
     echo "This is a test file in a subdirectory." > testdir/subdir/subfile.txt
     zip -er testdir.zip testdir
     ./bkcrack/bkcrack -C testdir.zip -c testdir/subdir/subfile.txt -p testdir/subdir/subfile.txt
     ```
     - Output:
       ```
       bkcrack 1.7.0 - 2024-05-26
       Data error: plaintext offset 0 is too large.
       ```

**Environment:**

- `bkcrack` version: 1.7.0
- `macOS` version: 14.6.1

It seems like the issue might be related to how `bkcrack` handles files within subfolders in the ZIP archive. The error message suggests that there is a problem with the plaintext offset, but the exact cause is unclear for me :)

Any guidance on how to resolve this issue or further diagnose the problem would be greatly appreciated!

**Comment by kimci86** [comment]
Hello,
You cannot use `testdir/subdir/subfile.txt` as known plaintext in your example. It does not match the content of the archive before encryption because it is compressed (and then encrypted) in the archive.

If you run `bkcrack -L testdir.zip`, you will see:
```
Archive: testdir.zip
Index Encryption Compression CRC32    Uncompressed  Packed size Name
----- ---------- ----------- -------- ------------ ------------ ----------------
    0 None       Store       00000000            0            0 testdir/
    1 ZipCrypto  Store       48375321           43           55 testdir/rootfile.txt
    2 None       Store       00000000            0            0 testdir/subdir/
    3 ZipCrypto  Deflate     7d8f7556           39           50 testdir/subdir/subfile.txt
```

`testdir/subdir/subfile.txt` is compressed (Deflate).
To run a known plaintext attack on this, you need to compress your file to get corresponding compressed data.

Alternatively you could use `testdir/rootfile.txt` directly to run an attack because it is not compressed (Store).

I have to admit the issue here is the error message is not explaining the problem. It makes sense when you know about the encryption header and that you can provide a negative offset, but I guess this is too technical for most users.
I should spend some time to make the errors more useful.

**Comment by infinity1234** [comment]
Hello,
Thank you so much for your detailed response! I really appreciate the time you took to explain the situation.

If I understand correctly, the issue arises because if the file are in the subfolder it's compressed before being encrypted.

So if I want to specifically attack a compressed file within a subfolder, I first need to compress the matching file myself using the same method (Deflate) before using it as the known plaintext. Does that sound correct? 

Do you have any specific recommendations on how to match the compression exactly to the one used in the ZIP archive, 
For example, if I want to match the compression used by macOS when creating a ZIP file, are there any specific commands or tools you would suggest?

Here’s what I’m thinking:

1. Compress the file manually:
   ```bash
   gzip -c testdir/subdir/subfile.txt > subfile_compressed.gz
   ```

2. Use the compressed data as the known plaintext:
   ```bash
   ./bkcrack/bkcrack -C testdir.zip -c testdir/subdir/subfile.txt -p subfile_compressed.gz
   ```

Does that sound correct?
Once again, thank you for your invaluable help.

**Comment by kimci86** [comment]
> Thank you so much for your detailed response! I really appreciate the time you took to explain the situation.

You are welcome!

> If I understand correctly, the issue arises because if the file is in a subfolder, it is compressed before being encrypted.

Not exactly. You encountered an issue because the file is compressed, but being in a subfolder is not the reason why it is compressed. It depends on the contents of the file, whether compression can make the file any smaller or not.

> I first need to compress the matching file myself using the same method (Deflate) before using it as the known plaintext. Does that sound correct?

Yes, that is correct.

> Do you have any specific recommendations on how to match the compression exactly to the one used in the ZIP archive, 

In your example, because you know you used `zip` to make the encrypted archive, you can simply use the same program `zip` again, but without encryption this time, to get the correct compression.
Then you can load data from within that archive with bkcrack using -P option:

```
zip plain.zip testdir/subdir/subfile.txt
./bkcrack/bkcrack -C testdir.zip -c testdir/subdir/subfile.txt -P plain.zip -p testdir/subdir/subfile.txt
```

In general, when you don't know what tool was used to make the encrypted archive, you would try using `zip` or `7z` (7-zip) or maybe other tools with various compression levels until you use the right compression tool and settings. One way to quickly discard wrong combinations is the compressed file size. You must have: $p + 12 = c$ where $p$ is the compressed size you get and $c$ the packed size in encrypted archive. This 12 bytes gap is due to the encryption header present in encrypted zip files as per zip file format specification.
