### ISSUE TITLE
How to deal the case of a zip with a folder

### ISSUE THREAD

**Issue by betterzyh** [kimci86/bkcrack#134]
zip archive, there is a folder, encrypted files are stored in this folder, this situation with bkcrack decryption, will prompt “Zip error: found no entry named ‘entry file’.” How to deal with this situation? Thank you.
use:
bkcrack -C bb.zip -c file1.dat -p plain.txt 
prompt:
Zip error: found no entry named ‘file1.dat’.”
Actually, “file1.dat” is in the secondary folder of bb.zip.

I'm using a translation program, it may not make sense, sorry!

**Comment by kimci86** [comment]
Folders hierarchy is encoded in ZIP archives by naming entries with a path containing folder names.
For example, in there is a file named `file1.dat` in a folder named `files`, then the entry name would be `files/file1.dat`.

You can see the full name of entries with `bkcrack -L bb.zip`.
Then use the full entry name in the command: `bkcrack -C bb.zip -c folder_name/file1.dat -p plain.txt`

If the entry name contains non-ASCII characters that make it challenging to copy or type, then you can use the entry index instead of the entry name. Let's assume the index for `file1.dat` in `bkcrack -L bb.zip` output is 42, then you would run this: `bkcrack -C bb.zip --cipher-index 42 -p plain.txt`

**Comment by betterzyh** [comment]
Thanks so much, it worked!
Both methods you provided worked!
Thank you so much for your reply!

**Comment by betterzyh** [comment]
Thanks so much, it worked!
Both methods you provided worked!
Thank you so much for your reply!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kimci86/bkcrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月25日(星期三) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kimci86/bkcrack] How to deal the case of a zip with a folder (Issue #134)






Folders hierarchy is encoded in ZIP archives by naming entries with a path containing folder names.
For example, in there is a file named file1.dat in a folder named files, then the entry name would be files/file1.dat.

You can see the full name of entries with bkcrack -L bb.zip.
Then use the full entry name in the command: bkcrack -C bb.zip -c folder_name/file1.dat -p plain.txt

If the entry name contains non-ASCII characters that make it challenging to copy or type, then you can use the entry index instead of the entry name. Let's assume the index for file1.dat in bkcrack -L bb.zip output is 42, then you would run this: bkcrack -C bb.zip --cipher-index 42 -p plain.txt
