### ISSUE TITLE
How to recover jpegs

### ISSUE THREAD

**Issue by ze-hans** [kimci86/bkcrack#18]
Hi, I tried applying the tutorial but failed.

First, I have a zip archive (pkzip, deflated) containing pictures that I would like to recover.
`zipdetails` yields:
```
00000000 LOCAL HEADER #1       04034B50
00000004 Extract Zip Spec      14 '2.0'
00000005 Extract OS            00 'MS-DOS'
00000006 General Purpose Flag  0001
         [Bit  0]              1 'Encryption'
         [Bits 1-2]            1 'Maximum Compression'
00000008 Compression Method    0008 'Deflated'
```
I was not able to recover with `hashcat` and `John the Ripper` so far, which is why I found this project.

To test the cracking procedure, I created a sample zip file (`3.zip`) containing two images (`camera__image_00000019.jpg`, `camera__image_00000020.jpg`) to test the procedure of the tutorial with compressed jpg files instead of svg files. 
As I'm on Linux the `zipdetails` are a little different in the OS section, however the rest seems to match:
```
000000 LOCAL HEADER #1       04034B50
000004 Extract Zip Spec      14 '2.0'
000005 Extract OS            03 'Unix'
000006 General Purpose Flag  0001
       [Bit  0]              1 'Encryption'
       [Bits 1-2]            1 'Maximum Compression'
000008 Compression Method    0008 'Deflated'
```

When looking at the header, it seems the header is typically
```
00000000: ffd8 ffe0 0010 4a46 4946 0001 0100 0001  ......JFIF......
00000010: 0001 0000 ffdb 0043 0006 0405 0605 0406  .......C........
00000020: 0605 0607 0706 080a 100a 0a09 090a 140e  ................
00000030: 0f0c 1017 1418 1817 1416 161a 1d25 1f1a  .............%..
```

Using the `unzip -Z -v 3.zip | grep CRC` or `7z l -slt 3.zip | grep CRC` I got the crc sums:
```
32-bit CRC value (hex):                         e36b1447
32-bit CRC value (hex):                         f07353a1
```

Then I created the plaintext files twice with
`echo -n -e '\xe3\xff\xd8\xff\xe0\x00\x10\x4a\x46\x49\x46\x00\x01' > 3.zip_plain.txt`
and to use more bytes with
`echo -n -e '\xe3\xff\xd8\xff\xe0\x00\x10\x4a\x46\x49\x46\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x43\x00\x06\x04\x05' > 3.zip_plain2.txt`

While the second was obviously faster, both did not work to recover the keys with
`./bkcrack -C 3.zip -c camera__image_00000019.jpg -p 3.zip_plain.txt -o -1`
and
`./bkcrack -C 3.zip -c camera__image_00000019.jpg -p 3.zip_plain2.txt -o -1`

What did I miss? Any help is very appreciated.

**Comment by kimci86** [comment]
Hello,
Thank you for describing clearly your experiments. I understand that the problem here is to find correct plaintext.

You can not simply use a JPEG header as plaintext because the file is compressed (deflated) in the zip archive. You would have to guess what the JPEG header becomes after compression. It is very hard without knowing the whole file (or at least a big part) because of how deflate compression works. In the tutorial, this approach works because the SVG file is stored without compression (on purpose, by me).

Now, you can try two things as described in the tutorial. You can check if some other file in your encrypted archive is stored without compression. Then, it should be easy to guess enough plaintext.
Otherwise, try to find a whole file unencrypted somewhere (e.g. online or from a backup somewhere) to generate plaintext by compressing it.

**Comment by ze-hans** [comment]
Thank you for the quick response and clarification. Obviously I did not read the tutorial well enough...

> You can check if some other file in your encrypted archive is stored without compression. Then, it should be easy to guess enough plaintext.
Sadly, there is no plaintext file in the archive.

> Otherwise, try to find a whole file unencrypted somewhere (e.g. online or from a backup) to generate plaintext by compressing it.
I have none of the files anywhere so I guess this leaves me with bruteforcing. :/

Thanks again for the clarification of how this attack works.
