### ISSUE TITLE
Password cracking problem in ZIP file using BKCRACK

### ISSUE THREAD

**Issue by kokosz887** [kimci86/bkcrack#24]
I would like to crack a password in a .zip file I created a few years ago and forgot my password. The compression algorithm is ZipCrypto Deflate.

There is only one file in MYFILE.zip - ABCD.pdf. I have an older copy of this PDF that is identical to the one that has a password of about 90%.

I tried to use BKCRACK. I opened the MYFILE.zip file in the HxD program and saw the header of the zip file in HEX format (50 4B 03 04) and the name ABCD.pdf in HEX format (41 42 43 44 2E 70 64 66) - offset 30. Thanks to this I have 12 bytes known text.

Then I used the command:

echo -n "ABCD.pdf" > plain.txt

time bkcrack -C MYFILE.zip -c ABCD.pdf -p plain.txt -o 30 -x 0 504B0304 > 1.log & tail -f 1.log

Unfortunately the result is:
[1] 5849
bkcrack: command not found
real 0m0.220s
user 0m0.078s
sys 0m0.041s

Please help, am I doing something wrong or is my file unblockable?

**Comment by kimci86** [comment]
Hi, the error message you see means that you are not running bkcrack. You should either install it on your system, or launch it with a path to the executable (for example `./bkcrack` if it is located in the current folder).

Then, the plaintext you want to use is not suitable. It is part of the file header in the zip archive. The file header is not encrypted so it cannot be used to get information about the encryption. The plaintext must be a part of the encrypted data as it was before encryption (which means compressed with deflate in your case).

So, I suggest you create a zip file `plain.zip` containing the old version of `ABCD.pdf` without password and use it as your plaintext. You should use the same compression settings you used for the encrypted archive (or try different settings if you do not remember).
Then, assuming bkcrack executable is in the current folder, run:
 `./bkcrack -C MYFILE.zip -c ABCD.pdf -P plain.zip -p ABCD.zip -t 12`

We can hope that the difference between the old and new versions of `ABCD.pdf` is small enough so that the compressed data will match at least for the 12 first bytes. It might not work because of the deflate compression: a small change in the input data can generate a completely different compressed data.
The parameter `-t` tells how many bytes to use (at least 12). The more bytes you use, the faster the attack will terminate, but also the less likely it is to be successful.

A plaintext attack might not work in you case. I suggest you also try dictionary of brute force attacks with hashcat or john the ripper.
Let me know if you need more help.

**Comment by kimci86** [comment]
@kokosz887 Did you manage to make some progress? Do you need more help? I will close this issue otherwise.
