### ISSUE TITLE
Zip error: found no entry

### ISSUE THREAD

**Issue by simongcx** [kimci86/bkcrack#62]
I'm trying to recover a password protected zip file where the full path name of the files was incorporated into the zip file when it was created (e.g. "C:\Temp\temp.txt"). bkcrack seems not to be able to find file, instead giving this error:

_Zip error: found no entry [filepath] in archive [zipfilename]_

Not sure if this is a limitation of the tool or user error. Grateful for input.

**Comment by kimci86** [comment]
Hello,
Make sure to pass exactly the filename used in the archive.
As choosing an entry by name has been reported to be a challenge is some cases, for example when encoding non ASCII characters is involved, I am working on an alternative which is to choose an entry by index (#60). It is not ready yet but it is coming soon™.

In the meantime, could you share the command line you used and the resulting error message? If it contains sensitive information you do not want to share with the entire internet, you can send it to me by email.
Thank you for your feedback!

**Comment by kimci86** [comment]
With the new version 1.4.0, you can now use an index to specify which entry to load.
Instead of `-c` or `-p` options, you can use `--cipher-index` or `--plain-index` respectively followed by the index of the entry you want to load.
To know which index to specify, first run `bkcrack -L your_archive.zip` and get the index from the first column of the printed table, on the line of the entry you want.

I close this issue as I expect this to solve your problem, but feel free to reopen if I am mistaken.
