### ISSUE TITLE
Unable to get the file status (STAT) of 'bkcrack': there is no file or directory

### ISSUE THREAD

**Issue by Dr34nn** [kimci86/bkcrack#64]
/desktop/bkcrack
cp bkcrack /usr/sbin/bkcrack

**Comment by kimci86** [comment]
Hi, so this the same issue as #63. Sorry, I should have been more patient before closing it. Anyways, you could have reopened it instead of opening a new one with the exact same information.

Now could you answer the questions I had:
What you are trying to do? What did you try already?

As I understand, you are trying to install bkcrack by using wrong commands you took from somewhere.
Please, explain your issue. Otherwise, I cannot help you.

**Comment by kimci86** [comment]
As there is no feedback, I close this issue. Feel free to reopen if it is still an issue.
