### ISSUE TITLE
Data error: ciphertext is smaller than plaintext

### ISSUE THREAD

**Issue by X1foideo** [kimci86/bkcrack#70]
Hi,
I'm trying to decrypt a zip where this contains a txt containing (I am sure about this):
- first line
- second line

Assuming this, I know part of the first line (I know how it begins) and i know entirely the second line, i know the len and of course the chars.
So now i have two problems:
1) I don't know the exact len of the first line so I can't assign a specific offset
2) Assuming that the second  line is composed of, multiple "a" (1000), when I set an offset of 200, and a plaintext of 100 "a", I get

> Data error: ciphertext is smaller than plaintext

**Comment by kimci86** [comment]
Hello,
Can you first check if the encrypted archive uses compression or not?
Running <code>bkcrack -L <i>your_encrypted_archive.zip</i></code> will tell you what compression algorithm is used, or `Store` if no compression is used.

If ciphertext is compressed, you have to compress plaintext the same way which can be very hard or impossible if you know only a part of it. The only difference between ciphertext and the portion of known plaintext you provide must be encryption.
I suspect ciphertext is compressed (probably with Deflate compression) and you provide uncompressed plaintext, so ciphertext would indeed be too short compared to provided plaintext, hence the error message.

> I don't know the exact len of the first line so I can't assign a specific offset

The encrypted file size is visible from the zip entry metadata (named "Packed size" in `bkcrack -L` output) so you can derive the correct offset like so: $\mathrm{suffix\ offset} = \mathrm{ciphertext\ packed\ size} - 12 - \mathrm{plaintext\ suffix\ size}$
(Minus 12 because encrypted data starts with a 12-byte encryption header before actual data.)

**Comment by X1foideo** [comment]
Sincerely Thanks, I didn't notice that changing the content of the second line the algorithm switched from Store to Deflate.
And secondly, thanks for the hint about the suffix_offset.
