### ISSUE TITLE
1.5.0 does not find keys for a complete file

### ISSUE THREAD

**Issue by A-Kazak** [kimci86/bkcrack#85]
Greetings!

  I use bkcrack 1.5.0 - 2022-07-07 with the attached pair of files, where **plain.zip** contains the complete file stored inside **encrypted.zip**.
The following call command:
`bkcrack --cipher-zip encrypted.zip --cipher-index 2 --plain-zip plain.zip --plain-index 2 -e
`
gives a negative response:
_Data error: ciphertext is smaller than plaintext._

What is my mistake?

Thank you.

[encrypted.zip](https://github.com/kimci86/bkcrack/files/10368754/encrypted.zip)
[plain.zip](https://github.com/kimci86/bkcrack/files/10368753/plain.zip)

**Comment by kimci86** [comment]
Hi, by inspecting both archives with `bkcrack -L`, we can see archives most likely contain the same file (uncompressed size and CRC match) with one encrypted with ZipCrypto and one not encrypted. So far so good.

```
Archive: encrypted.zip
Index Encryption Compression CRC32    Uncompressed  Packed size Name
----- ---------- ----------- -------- ------------ ------------ ----------------
    0 None       Store       00000000            0            0 Xradia Setup/
    1 None       Store       00000000            0            0 Xradia Setup/HyperTerminal/
    2 ZipCrypto  Deflate     0015620f       347136       158259 Xradia Setup/HyperTerminal/hypertrm.dll
```
```
Archive: plain.zip
Index Encryption Compression CRC32    Uncompressed  Packed size Name
----- ---------- ----------- -------- ------------ ------------ ----------------
    0 None       Store       00000000            0            0 Xradia Setup/
    1 None       Store       00000000            0            0 Xradia Setup/HyperTerminal/
    2 None       Deflate     0015620f       347136       161495 Xradia Setup/HyperTerminal/hypertrm.dll
```

However, compressed size do not match. That is why there is an error message.
Ciphertext and plaintext need to be compressed the same way. If we do not know how the ciphertext was compressed, we can try various compression tools and parameters until we find the right one. Let's try compressing the file using 7zip with default parameters.

```bash
unzip plain.zip
7z a plain-7z.zip "Xradia Setup/HyperTerminal/hypertrm.dll"
bkcrack -L plain-7z.zip
```
Let's see the resulting compressed size:
```
Archive: plain-7z.zip
Index Encryption Compression CRC32    Uncompressed  Packed size Name
----- ---------- ----------- -------- ------------ ------------ ----------------
    0 None       Deflate     0015620f       347136       158247 Xradia Setup/HyperTerminal/hypertrm.dll
```
Great, 158247 bytes is what we want. The encrypted version is 158259 bytes (12 more) but, because it is encrypted with ZipCrypto, it starts with 12 bytes of encryption header. We are all set!
Running bkcrack with this compressed data works. While at it, we can get the password too:
```
bkcrack --cipher-zip encrypted.zip --cipher-index 2 --plain-zip plain-7z.zip --plain-index 0 -r 12 ?p
```

I hope it helps! Let me know if you have other questions. Otherwise feel free to close this issue.

PS: I do not know what Xradia is about and what you are doing but I do not recommend stealing software :wink:

**Comment by A-Kazak** [comment]
Thank you very much for the prompt feedback.


Can you elaborate on the reasons why the packed size of 158259 versus 161495  is bad, but the packed size of 158259 versus 158247 is fine, please?
_Great, 158247 bytes is what we want. The encrypted version is 158259 bytes (12 more) but, because it is encrypted with ZipCrypto, it starts with 12 bytes of encryption header. We are all set!_

**Comment by kimci86** [comment]
> Can you elaborate on the reasons why the packed size of 158259 versus 161495 is bad, but the packed size of 158259 versus 158247 is fine, please?

To carry out a successful known-plaintext attack, we need the same data before and after encryption. So there must be no difference between the encrypted entry and the entry without encryption, besides encryption of course. In particular, the compression algorithm, the used implementation and parameters must be the same, because encryption is applied to compressed data.

One way to be rather confident that compression is the same is to have the same compressed size.
Now, a subtlety is that the data packed in a ZIP archive for an entry encrypted with ZipCrypto consists of a 12-bytes header followed by actual compressed and encrypted data. This is determined by the ZIP format specification.

In your case, it means that the encrypted entry of 158259 bytes is made of 12 bytes of encryption header and 158247 bytes of encrypted compressed data. So the goal to run a successful attack is to find what compression tool with what parameters get the known file compressed into 158247 bytes. In your case, 7-zip with default parameters did it.

**Comment by A-Kazak** [comment]
> In your case, it means that the encrypted entry of 158259 bytes is made of 12 bytes of encryption header and 158247 bytes of encrypted compressed data. So the goal to run a successful attack is to find what compression tool with what parameters get the known file compressed into 158247 bytes. In your case, 7-zip with default parameters did it.

In other words we should ensure that 12 bytes of the encryption header of the compressed and then encrypted file are exactly the same to that of plain compressed file. Did I get the point correctly?

**Comment by kimci86** [comment]
> In other words, we should ensure that 12 bytes of the encryption header of the compressed and then encrypted file are exactly the same as that of the plain compressed file. Did I get the point correctly?

No. Let me summarize with some diagrams.

Adding a file in an encrypted archive goes roughly like this:
```mermaid
flowchart TD
    header["encryption header (12 bytes)"] --> pre_enc["data to encrypt (12 + N bytes)"]
    input[input data] -->|deflate compression| comp["compressed data (N bytes)"]
    comp --> pre_enc
    pre_enc -->|encryption| output["packed data (12 + N bytes)"]
style comp stroke:#F00
```
Adding a file in an archive without encryption roughly goes like this:
```mermaid
flowchart TD
    input[input data] -->|deflate compression| comp[packed data]
style comp stroke:#F00
```

To run an attack, giving the compressed data (outlined in red above) is enough.
So given an encrypted entry of packed size (12 + N), the goal is to find compression parameters that create compressed data of length N.
Does that make sense?

**Comment by A-Kazak** [comment]
> Does that make sense?
I got it now, actually!
Thank you for providing the nice drawings.

Why does the header not contain compression method(s) and their parameter(s)?

**Comment by kimci86** [comment]
> Why does the header not contain compression method(s) and their parameter(s)?

Encryption header does not contain metadata (except last byte). It is mostly random. Its purpose is to make encryption a little less weak.

That being said, ZIP files do store metadata about each entry before packed data (name, size, compression algorithm, etc). However, compression can be tuned to be faster or to compress more and can be implemented in different ways. Those parameters are not needed to decompress data so they are not stored as ZIP entry metadata. This is why we may have to guess and try different compression tools and parameters to find which combination was used.

**Comment by A-Kazak** [comment]
Got it!
Thank you for expaining this.
