### ISSUE TITLE
Using plain text file without compressing to ZIP

### ISSUE THREAD

**Issue by A-Kazak** [kimci86/bkcrack#87]
Greetings!

I use bkcrack 1.5.0 - 2022-07-07 **encrypted.zip** prepared using ZipCrypto Deflate method.
**encrypted.zip** contains a single PDF file with the following header:
```
%PDF-1.4
%**XXXX**
1 0 obj
<<
/Creator (
```
where XXXX is four unknown characters.

How do I use a part of the plain text file starting from "1 0 obj ..." with a length of more than 12 bytes without compressing the plain text file to a ZIP archive (and guessing the correct compression method and parameters)?

Thank you.

**Comment by kimci86** [comment]
The encrypted file was compressed before encryption (ZipCrypto Deflate method) so valid plaintext must be compressed data. You have to get compressed data somehow.
That being said, if you have so little known uncompressed data, compressing it as if it was part of the complete file is close to impossible because the compression outcome depends very much on the rest of the file (which is unknown).

I don't think a known-plaintext attack can be used in your case unless you know a significant part of the file before compression. You might want to try bruteforce or dictionnary-based password cracking instead using other tools like as [john the ripper](https://www.openwall.com/john/) or [hashcat](https://hashcat.net/hashcat/).
