### ISSUE TITLE
Password length syntax

### ISSUE THREAD

**Issue by mastereworm** [kimci86/bkcrack#88]
Readme provides an example of original password recovery:

`bkcrack -k 18f285c6 881f2169 b35d661d -r 11..13 ?p`

But if I use it,  length value as a range with two dots (x..y) has no effect, bkcrack still calculates all previous lengths from 0 to y

**Comment by kimci86** [comment]
Hi, I am assuming you use version 1.5.0. What you noticed is because the readme documents this feature of choosing a password length range that is not included in the latest released version yet. I will try to make a new release soon.
In the meantime, if you want this feature, you can compile the latest in-development version yourself. Feel free to ask if you need help to do so.

**Comment by mastereworm** [comment]
Clear, thankyou

**Comment by kimci86** [comment]
I finally released version 1.6.0
