### ISSUE TITLE
invalid data: ciphertext is smaller than plaintext

### ISSUE THREAD

**Issue by ACH1980** [kimci86/bkcrack#9]
This is not a bug report (I think it's no bug), but I would like to know what I'am making wrong... Below is a screenshot from the terminal...
![image](https://user-images.githubusercontent.com/39656381/77853177-01353300-71e3-11ea-99f3-ba20dc600dcc.png)

**Comment by Aloxaf** [comment]
The cipher **file** you specified seems to be a directory.

**Comment by kimci86** [comment]
Hello,
As @Aloxaf pointed out (thank you!), you specified a directory name for the `-c` parameter.
A directory on its own contains only some metadata in zip archives, but it contains no data to carry out the attack, hence the error.
I guess you should append `LICENSE` to the `-c` argument so it points to a file entry in the archive which would be the encrypted version of your plaintext.
Does it help?

**Comment by ACH1980** [comment]
Yeah, what a dump mistake. I'll try  it and close this issue on success...

**Comment by ACH1980** [comment]
It seems to be working, but it produced the following output:
![image](https://user-images.githubusercontent.com/39656381/78291258-62cc0900-7525-11ea-9e95-6d31e2d78b6e.png)


What can I do to get back my backup?

**Comment by kimci86** [comment]
Here are some steps for you.

1. Get some metadata about the ciphertext and plaintext using 7zip
`7z l -slt <archive.zip> <path/to/LICENCE>`
You want to look at CRC, Packed size and Method.

2. Make sure that the encrypted archive uses the legacy encryption algorithm.
The ciphertext Method field should contain `ZipCrypto`. Otherwise, bkcrack cannot be used.

Then, bkcrack can fail if the plaintext is not identical to the ciphertext just before encryption, i.e. after compression. It might be because the data in the known file `LICENCE` is wrong, or because it was not compressed exactly with the same parameters used in the encrypted archive.

3. Check that the files before compression match by checking they have the same CRC value.

4. Check that the files after compression match by checking they have the same compression method (usually it is Deflate) and the compressed size.
You should have: `plaintext packed size + 12 = ciphertext packed size`
Try to compress `LICENSE` with different compression levels if not.

**Comment by ACH1980** [comment]
![image](https://user-images.githubusercontent.com/39656381/79073986-049fe280-7cea-11ea-8a4e-4593fe7eb539.png)

If I'am right, this is good, isn't it?

**Comment by kimci86** [comment]
It looks perfect, bkcrack should be able to find the encryption keys... As it does not, you can try to use the option `-t` to shorten the Z reduction step which seems to reduce to much. Something like `-t 1000` should not reduce too much and still be fast. Use a smaller value for -t if it still does not work.

**Comment by ACH1980** [comment]
I'll try. And many thanks for your intense help 🙏

**Comment by kimci86** [comment]
Oh, I understand. Your backup archive is huge, so the Zip64 format is used. It is not (wet) supported by bkcrack. You should try to use @Aloxaf 's fork https://github.com/Aloxaf/rbkcrack

**Comment by ACH1980** [comment]
Ah thank you 🙏

**Comment by ACH1980** [comment]
It seems to work, but can I also decipher the whole zip file or do I need to make it file for file? The last option would be very hard :-(

**Comment by ACH1980** [comment]
Ah wait, I need to decipher the zip and not the files in it, right?

**Comment by ACH1980** [comment]
If yes, what's wrong now?

![image](https://user-images.githubusercontent.com/39656381/79076518-0a51f400-7cfb-11ea-893b-c75395dc7dea.png)

**Comment by kimci86** [comment]
Full archive decryption in not (yet) implemented in bkcrack, it can do it file by file, but hopefully @Aloxaf also did a fork of 7-zip to extract an encrypted archive by providing the keys instead of a password. https://github.com/Aloxaf/p7zip

**Comment by ACH1980** [comment]
Oh nice. Thanks a lot :-)

**Comment by ACH1980** [comment]
You have rescued my backup! Many thanks! 😊🙏
