### ISSUE TITLE
Fail to decode because of an unknown additional byte

### ISSUE THREAD

**Issue by noname01t1** [kimci86/bkcrack#92]
I'm now testing to decode a zip file using "ZipCrypto Deflate" algorithm and with a png file inside. The png header is `8950 4e47 0d0a 1a0a 0000 000d 4948 4452`. I'm trying to write it into a file using free hex editor. However, the file should be 8 bytes. But when I want to decode the zip file. 8 bytes turns out to be 9 bytes. 
```
bkcrack 1.5.0 - 2022-07-07
 Z reduction using 9 bytes of known plaintext
```
I'm really confused about that.

png_header file: https://wormhole.app/KKj70#dqZJms5wmDdiJgdxwl3O6g

**Comment by kimci86** [comment]
About the file size, the PNG header file you use is 16 bytes, not 8 bytes.
About why 9 bytes are used for reduction: bkcrack runs in roughly two steps. First, use contiguous bytes minus 8 to reduce the search space (Z reduction), then explore the resulting search space using the remaining 8 contiguous byte.
Here you provide 16 bytes. One more byte can be derived from ZIP metadata, and it is done automatically. 17 bytes are known. 9 are used for the Z reduction step and 8 for the step after.

Now, note that using this PNG header will now work on a ZIP file using ZipCrypto Deflate. The PNG header corresponds to data without compression, and bkcrack needs known data before encryption. Because deflate compression algorithm is used, data before encryption means data after compression.

**Comment by kimci86** [comment]
As there are no further comments, I assume that the question has been answered. Feel free to reopen if I am mistaken.
